### ISSUE TITLE
Full story / mix panel

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#101]
Got my first email from Full Story this morning so I can see thats now been implemented. Thank you.

I spoke with Full Story and they have a simple integration with MixPanel which is perfect for us. Please can this be implemented (here's the instructions)

https://partners.fullstory.com/integrations/solution/792/mixpanel

**Comment by jhamlett** [comment]
@ZiggyAtl  I have activated the Mixpanel integration on the Full Story account. Full Story was only tracking activity on a development instance of the site up until this afternoon but it now should track the staging site.
