### ISSUE TITLE
Debug Contact Form Notifications 

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#116]
Bill is not receiving notifications based on form logic in cognito

**Comment by jonathanwburr** [comment]
@ZiggyAtl I made some adjustments to form logic. I just submitted 3 options. Let me know if you are receiving notifications

**Comment by ZiggyAtl** [comment]
Thanks. I received them, but I also got multiple ones with some wrong details (wrong recipient, wrong subject etc). I can see you also got those too, so you'll see what I mean. We only need each one going to the correct email recipient

**Comment by jonathanwburr** [comment]
@ZiggyAtl Ok I think I tracked down the issue. Resent some tests.

**Comment by ZiggyAtl** [comment]
I didn't receive any emails
