### ISSUE TITLE
#DAB receipt / tax exemption letter

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#119]
@paulstroot are you thinking of using a standard Shopify order acknowledgement / receipt / invoice document for this, which we can add custom wording to? Thought I'd ask that question first as it would be useful for you to send me that document, if you are planning on doing that, and I can see what we need to do to customize that rather than try and create something from scratch.

**Comment by paulstroot** [comment]
@ZiggyAtl , I was actually waiting for you to let us know what sort of working you would like to use for this email. I think you'll need to create this from scratch, as we don't have any examples to reference.

**Comment by ZiggyAtl** [comment]
@paulstroot please could you resend me the latest version of the other email that goes out. Want to make sure I don't duplicate anything

**Comment by ZiggyAtl** [comment]
Hopefully this document outlines the best way to split up all the purchase info and next steps in to two separate emails.
[Emails after a purchase.docx](https://github.com/ocupop/comission-shopify-hydrogen/files/9832182/Emails.after.a.purchase.docx)

**Comment by paulstroot** [comment]
@ZiggyAtl , We have a solution set up to be able to send emails from our application without having to go through Shopify's notification email setup. This solution uses a third-party email sending service called "SendGrid". For security reasons, in order to be able to send emails from a certain domain name, like "sales@CoMission.art" or "bill@comisson.art", we need to make some updates to the Domain DNS settings to prove ownership and allow SendGrid to send emails from the CoMission domain name.

To do this, I will need to access the goDaddy account where CoMission.art is hosted. There is 2-factor authentication set up on this account, so when I try to log in a code will be sent to your phone. Can you please tell me a time when you will be available to send me this authentication code?

**Comment by ZiggyAtl** [comment]
@paulstroot sorry just seen this. If you want to try it now I can send you the code

**Comment by ZiggyAtl** [comment]
@paulstroot That look great. A couple of things;
1) For the multi museum version it should say "The details of your donations are below" (plural). If this is problematic and you just want to use one set of wording for both the single and multi donations, you could say "Your donation details are below." and that would work for both.
2) Under each donation amount it should have the wording "No goods or services were provided for this donation." OR a description of what goods were supplied. Is it possible to have a free type box in the set up for each artwork where this info can be added, and therefore adapted for each individual artwork, which will then print under the Amount on the receipt? If not please can you have the phrase print out on each invoice, under the amount. 
3) It's not a requirement for the non profit organization to provide their address, but I've just remembered it is a requirement of anyone claiming a tax deduction to list the non profits organizations address. Therefore many people get it from the receipt. Is there anywhere in the museum admin/set up where they will be listing their address? If so can we take the info from that box to add to the receipt? If there's not, don't worry about it

**Comment by ZiggyAtl** [comment]
@paulstroot please can you send me emails of the latest format of the receipts so I can check them. thanks

**Comment by paulstroot** [comment]
TODO: if Tax ID does not exist for a museum, eliminate that line it the email receipt.

**Comment by paulstroot** [comment]
Here is a screenshot of the order confirmation email, and of the order email receipt. Tax ID is now being properly inserted into the email, and the text updates have been made.

![image](https://user-images.githubusercontent.com/52838369/200712984-c3605bd4-3ae8-445e-ad53-99519a4c44d4.png)

![image](https://user-images.githubusercontent.com/52838369/200713063-1c521f2c-0bcf-40a6-b65a-ff195becb53d.png)

**Comment by ZiggyAtl** [comment]
@paulstroot thanks for that. One more thing, and sorry to be picky on this one. Please can you close the gap in between the 'Thank you...' title and the bullet points a little (by about 50% of the current gap) and can you add another carriage return after the last bullet point (to make a touch more space in between that and the next paragraph). It just looked a little unbalanced when I looked at the current layout.

**Comment by paulstroot** [comment]
Update made. Here is a preview:

![image](https://user-images.githubusercontent.com/52838369/200925029-a5812c59-a4c0-4bfd-a7b3-4437170b597a.png)

**Comment by ZiggyAtl** [comment]
@paulstroot Not sure what happened with this one. Rather than the gap at the top being closed a bit, there is now a line of text that wasn't in there before (which we don't want). Also the bullet points don't have the museum and artist detail in there, however is that because this is just a test and the email isn't linked to a purchase?

**Comment by paulstroot** [comment]
Sorry. That was because I took the screenshot from the sample email that is displayed in Shopify. It's a little different than the actual email that gets sent because there is no shipping, and we have museum details in the real email. here is a screenshot of one of the emails that came in my inbox after a test order.

![image](https://user-images.githubusercontent.com/52838369/202058774-40c6bae9-1af6-49bd-99b4-a6bb56e501d0.png)

**Comment by paulstroot** [comment]
I can't see from your screenshot where the artist name is supposed to show up. It should be in the first bullet point, "You can now brag that you have a masterpiece by world renowned artist [ARTIST NAME] in your art collection."

Was it not there for you?

**Comment by ZiggyAtl** [comment]
@paulstroot Just over the View your Certificate button. It says "That Illustrious Feeling by             "

**Comment by paulstroot** [comment]
Ah ha! Thanks. I overlooked that one. I'll take care of that this afternoon and mark as ready for review once it's fixed.

**Comment by paulstroot** [comment]
This should be working correctly now. I just submitted a test order and the artist name came through in the email receipt.
