### ISSUE TITLE
Change on benefits page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#12]
https://comission-shopify-hydrogen-ocupop.vercel.app/pages/benefits  

Under the Community and Connection section, change the title of the right hand benefit to Virtual Meetups, and alter wording to “Meet your tribe online in community groups and metaverse meetups. Maybe even meet an artist or curator along the way.”

**Comment by ZiggyAtl** [comment]
I noticed an inconsistency in the headings. They are all lowercase apart from the first word. Therefore please make the A in Amazing lower case, and the M in Museum

**Comment by jonathanwburr** [comment]
@ZiggyAtl I updated the titling
