### ISSUE TITLE
Redirect new user to See Artworks (gallery)

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#121]
When a new user logs in and they go to their account, there is a button which says "Start Collecting". This should go to the See Artworks (Gallery) page, but instead it just goes to the homepage.

![Screen Shot 2022-10-13 at 8 08 36 PM](https://user-images.githubusercontent.com/112654923/195733982-497e876c-cdd1-403e-97c6-3569fd873952.png)

**Comment by paulstroot** [comment]
Done
