### ISSUE TITLE
DAB selection wording

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#124]
As we will be marking some dabs as 'unavailable', to create scarcity, I think we need to be consistent with the wording on any that the user can't buy (including those already sold). Therefore on the tool tip, could you replace the word SOLD for UNAVAILABLE

Also on the artwork page, can you use the word 'available' rather than 'left'. See where highlighted on the attached screenshot.

One other point, in the screenshot it says there are 25 of the 2400 dabs remaining, however when I go to select one there are a lot more than that available. So that counter doesn't seem to be working properly.

![Screen Shot 2022-10-17 at 12 28 30 PM](https://user-images.githubusercontent.com/112654923/196232200-14b46d38-e040-4b39-94ff-c6399ae7ba28.png)

**Comment by paulstroot** [comment]
Thanks. I'll make the updates to the wording. The numbers will be a little inconsistent right now because we're still in development on that feature.
