### ISSUE TITLE
Frequently Asked Questions (FAQ) Page Availability

### ISSUE THREAD

**Issue by alexjlahr** [ocupop/comission-shopify-hydrogen#125]
The FAQ page exists – https://store.comission.art/faq – but is currently not linked to from anywhere within the website.

What are our thoughts on making the 'How It Works' item within the nav behave as 'Partners' does, with a drop-down? I could also see us striking 'My Account' from the footer nav and replacing with 'Frequently Asked Questions' @paulstroot @tbeck @jonathanwburr 

Ideally, we would also have a CTA section added to the 'How It Works' page, too, but recognize that may be a larger lift. @jennyvanderheiden

**Comment by paulstroot** [comment]
I replaced the "Account" link in the footer with "FAQ"
