### ISSUE TITLE
How It Works page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#13]
https://comission-shopify-hydrogen-ocupop.vercel.app/pages/how-it-works  

- [x] At end of first segment change 'efforts' to 'work'

- [x] Change the second paragraph to begin with “Together with our partner Museums and Artists, we select….”

- [x] In the Connecting with Your Artwork section, there is the phrase "The full list of benefits is available here....." but there is no hyperlink there

- [x] At the bottom change the heading to "Experience v Investment"

**Comment by ZiggyAtl** [comment]
This is a design question for Jenny. There seems to be a lot of white space in between the 5 paragraphs explaining how it works. Could they be reduced 'slightly' (maybe 25%)?

**Comment by tbeck** [comment]
@ZiggyAtl - Opened new issue so we can close this one if the changes @jonathanwburr pushed are good?
