### ISSUE TITLE
'See Artworks' page link changes

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#135]
I've just realized that in various places the website doesn't show the potential buyer the details of the artwork, or explains what comes with it. It just goes straight to Select Your DAB, which is too premature. There are two easy fixes for this on the See Artworks page.

1) If an artwork is selected from the carousel it should go the Artwork page (e.g. https://comission-shopify-hydrogen-ocupop.vercel.app/products/heels-out), NOT to the current page which has stripped down info and a Select Your DAB button.

2) Where the artworks are listed underneath the carousel, they should have the same 'View Details' button that appears on the homepage, instead of the 'Select Your DAB'.  That then takes them to the artwork page, where the user sees all the details.

**Comment by ZiggyAtl** [comment]
@jonathanwburr the second part of the request has been done, thanks. 

However the first one hasn't. If someone clicks on the artwork in the carousel it doesn't go straight to the artwork page. It brings up stripped down details of the artwork and they then have to click the View details

**Comment by paulstroot** [comment]
Hi Bill, let's discuss this in our meeting today.
