### ISSUE TITLE
Benefits to features + a couple of other text changes.

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#136]
To help overcome some of the confusion initial viewers have had I want to make a couple of text changes (and reduce the amount of text), and use the word FEATURES instead of BENEFITS throughout the site. I've listed the text changes below. (B-F) means an area where we need the benefit to feature word change.

HOME PAGE;
- [x] (B-F) Under the word Experience in the second blue block/column
- [x] In the white box under the Now Available section, please change the words to 'See all available artwork'
- [x] In the Experience section, under the title, change it to 'Exclusive features for collectors'
- [x] Replace the wording in that section with the following;

Each CoMission artwork is made up of a number of unique pieces - Digital Art Blocks (DABs) from which you choose your own and buy a membership in the artwork. That purchase is a charitable donation to the museum which owns the physical artwork.

Your DAB is then your passport in to our community, letting you view the artwork on your own devices, show it off to friends, connect with fellow fans, and enjoy other exclusive features related to the artwork.

- [x] Wording under that (over the feature/icons) should say 'Each artwork includes a selection of these features'
- [x] White box should say 'Explore the features'
- [x] In the Foster section, remove the subtitle (Supporting the arts..) and the entire Ignite your passion for collecting section (and the match image). Then make 'Funding the future of art' the subtitle, followed by 
Because every purchase on the CoMission website is a charitable donation to the museum which owns the artwork, these valuable funds help the museum support local artists, expand their programs, develop their collections and diversify the art hung on their walls.
- [x] Also please increase the size of the text to be the same as the text in the Experience section.
OUR MISSION PAGE
- [x] Change the white box to say 'See how it works'
HOW IT WORKS PAGE
- [x] 'Connecting with your artwork' section should say;
In conjunction with the museum or artist, we put together a selection of unique features that are included with each artwork. The full list is available here (https://comission-shopify-hydrogen-ocupop.vercel.app/benefits), while each artwork listing notes the specific features that come with that artwork.
BENEFITS PAGE (CHANGE MENU BAR TO SAY FEATURES)
- [x] (B-F) first word in title
- [x] Second paragraph should say;
In conjunction with the museum or artist we choose a selection of unique features that are included with each artwork. The full list is available below, while each artwork listing will note the specific features that come with that artwork.
- [x] Change title from 'Benefits Breakdown' to 'Features'
- [x] Section at bottom - change benefits to features in the title, and where it appears in the paragraph below it.
MUSEUM PARTNERS PAGE
Change B-F in the link at the bottom of the page

The other suggestion I was given, which I think is a good one, is to replace the image in the Experience section with the image of the DAB coming out of the painting, which is part of the graphic in the How it Works section. I don't mean having the whole thing, just a static image like this

![Screen Shot 2022-10-19 at 9 41 16 PM](https://user-images.githubusercontent.com/112654923/196836564-b80fdb5f-8dbb-4ac2-b82d-e9632a2dab87.png)

**Comment by paulstroot** [comment]
Moving the last item about the image to a new issue.
#137

**Comment by ZiggyAtl** [comment]
Thanks @paulstroot  two things remaining;
The first action item still says Benefits. See screen shot
![Screen Shot 2022-10-20 at 12 49 16 PM](https://user-images.githubusercontent.com/112654923/197010290-4b49c690-c032-4a05-a640-04802cb9317a.png)

The link on the museum page (https://comission-shopify-hydrogen-ocupop.vercel.app/for-museums) still says benefits. 
![Screen Shot 2022-10-20 at 12 52 00 PM](https://user-images.githubusercontent.com/112654923/197010737-1d9ae02f-1a70-4f28-9cb9-33bb249cc00c.png)

**Comment by paulstroot** [comment]
Pushing that update to the live site now.
