### ISSUE TITLE
Updating wording on checkout confirmation page

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#141]
From Bill in Issue #108:
One thing, is the wording on the left hand side fixed or can it be modified. Ideally the wording under 'Your order is confirmed' should say 'You'll receive a confirmation email with your order details and tax receipt shortly'

![image](https://user-images.githubusercontent.com/52838369/197026444-b7d4e96f-b4e4-42a2-88c9-daf86b325062.png)

**Comment by ZiggyAtl** [comment]
@jonathanwburr I'm unable to check this as I can't process an order. If you've checked this as it's what I asked for I'm happy for you to close the issue. Or do you have a way for me to process sample orders please?

**Comment by jonathanwburr** [comment]
@ZiggyAtl here's some instructions for processing test orders
https://gyazo.com/6f7adc5de17b64e8a165f00cadd6d0eb
