### ISSUE TITLE
Pricing level names

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#142]
One the call I noticed that the pricing still says Base pricing, then tier 1, tier 2 etc. Can we eliminate the phrase 'base price', so that the lowest price is tier 1, then tier 2 etc?

**Comment by paulstroot** [comment]
Yes. Update made. This is just some old naming that carried over from when the product was first created weeks ago. Newly created artworks should default to "Pricing Tier 1" being the first pricing tier created.
