### ISSUE TITLE
Remove logos

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#149]
Please could you remove the 4 museum logos at the bottom of this age as they are actual museums and it implies they have signed up with us, which they haven't
https://comission-shopify-hydrogen-ocupop.vercel.app/for-museums

**Comment by paulstroot** [comment]
@jennyvanderheiden and @tbeck , Tagging you for visibility. Should we replace these logos for some fake logos? Thoughts?

**Comment by jennyvanderheiden** [comment]
Maybe we should just remove until we have museums? to avoid that same confusion

**Comment by ZiggyAtl** [comment]
@jennyvanderheiden @paulstroot agree with Jenny, please remove them.
thanks
