### ISSUE TITLE
Emails for "Submit for Approval" and "Change Request"

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#150]
I've implemented some emails for the Museum Admin for when they Submit new artwork for approval, or request changes to artwork that has already gone live. These emails will be received by a CoMission admin.

Question: Should these emails be sent to "store@comission.art"? Or a different email address?

Attached are screenshots of the emails Please review the wording carefully and feel free to suggest any edits.

**Submit for approval:** (note: the "reply to Paul Stroot..." is because I was the logged in museum app user that submitted the request)
![image](https://user-images.githubusercontent.com/52838369/197849595-6589f537-d34d-4b15-883b-2a95fcb9fecd.png)

**Change Request:**
![image](https://user-images.githubusercontent.com/52838369/197849570-8bd81ff3-ab73-4414-b9ba-de29cdf817cd.png)

Adding @tbeck for visibility

**Comment by ZiggyAtl** [comment]
@paulstroot those emails are OK thanks. No edits needed. Please have them sent to support@comission.art
