### ISSUE TITLE
The "See Artworks' page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#16]
https://comission-shopify-hydrogen-ocupop.vercel.app/products

- [x] How does the carousel work when there are more than 2 pieces on? At the moment it just has two pieces which can be selected between

- [x] The filters need adding, to help the user narrow down their artwork choice.

- [x] If I click one of the artworks on the carousel and bring it to the front, there isn’t then a hyperlink on the title to take me to the artwork page

- [x] When I first select an artwork and click on Select your DAB it doesn’t allow me. Instead it takes me to the artwork page, and I've then got to select the Select your DAB option again.

- [x] That Illustrious Feeling is listed as being done by the wrong artist (both artworks show as being painted by Samual Wanjau).

**Comment by paulstroot** [comment]
I swapped the artists so the correct artist should now be assigned to the correct piece of art.

**Comment by ZiggyAtl** [comment]
Even though I've closed this one out I am assuming that the filters will be brought back once there is more art, as per our conversation just now.

**Comment by ZiggyAtl** [comment]
Reopening as I forgot the issue about having to select the DAB twice was still open. Ticked off the other aspects

**Comment by paulstroot** [comment]
I have an updated staged on development that will allow the DAB selector to open up from anywhere on the site. Just need to test before pushing up to staging.
