### ISSUE TITLE
Certificate substituting fonts

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#168]
I noticed that the fonts in the certificate got substituted on my Mac as soon as I downloaded it. This is a recent issue as it used to work fine. I have attached what it looks like once it is downloaded.

[certificates-certificate_Jv4QIJOzBmaabrCwZa3C.pdf](https://github.com/ocupop/comission-shopify-hydrogen/files/9932376/certificates-certificate_Jv4QIJOzBmaabrCwZa3C.pdf)

**Comment by tbeck** [comment]
It doesn't look like Pupeteer handles outlining fonts as part of their PDF configuration.

Looking into updating the font family to limit font variations. It is currently set to: `Helvetica Neue,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;`

**Comment by ZiggyAtl** [comment]
@tbeck don't know if this is related but I've noticed issues with helvetica neue on my mac. It was the font used for the pitch deck you guys put together, and whenever I try and save updates I get this
![Screen Shot 2022-11-10 at 8 37 19 AM](https://user-images.githubusercontent.com/112654923/201106263-d4efcf95-39a6-4a03-8803-4cbd50d90bba.png)

**Comment by tbeck** [comment]
Hi @ZiggyAtl - Thanks for flagging that warning. It is a related issue that is caused by the font selection. I discussed a fix for the certificate with Jon yesterday, but it looks like we should pull @jennyvanderheiden into the conversation to help provide an alternative solution for the pitch deck.

@jennyvanderheiden - Let's connect today and I can answer any questions you have regarding the issue.

**Comment by jennyvanderheiden** [comment]
Hi @ZiggyAtl 

I am attaching the fonts here so you have access to them and avoid this issue for your personal computer. [https://www.dropbox.com/s/0zx1vj63l7jkq31/HelveticaNeue.ttc?dl=0](url)

In regards to the Pitch Deck itself - downloading and sharing as a Powerpoint will run into these issues as you share with other that do not have this font installed on their computer. If you were to export as a PDF from the google Doc, I don't think you will run into the same issues as the fonts will be embedded, but unfortunately that is not the case with PP.

We can substitute the font for something similar (like Arial) but that will slightly take away from the look and feel of the branding using the Helvetica Neue font. I think through using the google doc and exporting as pdf, we can avoid this being a problem. I tested Arial out on slide 2 of this deck to do a guy check. [https://docs.google.com/presentation/d/1qHSVu6MCUN41HZic1gjMmXYSLAaGc06fxuUtqts5p_I/edit#slide=id.g122860d0641_0_27](url)

Let us know what you think!

**Comment by jonathanwburr** [comment]
@ZiggyAtl I made some updates to how fonts are loaded into the generated pdf downloadable document. 
Attached is the version that was generated on my machine which looked good on both Tom and Pauls machines as well. 
https://storage.googleapis.com/download/storage/v1/b/comission-application.appspot.com/o/certificates%2F6oeM8vpsc5rZBkhfPThA.pdf?generation=1668110781304129&alt=media
This is the Dab it was generated from if you can download and test
https://store.comission.art/dab/7273842147507-6oeM8vpsc5rZBkhfPThA

**Comment by ZiggyAtl** [comment]
@jonathanwburr thanks for this. There's a couple of differences between this and the original one, which I hope you can easily fix, and I took some pictures showing the two versions side by side to illustrate it. If you look at the headings, the font on the new version is condensed, and the characters are running in to, and merging, with each other. It looked much better on the original one. Also the text that explains the art and collector is lighter than it originally was, and doesn't stand out as much.  It would look better if it was bolder.

![IMG_5004](https://user-images.githubusercontent.com/112654923/201224742-befe4524-1806-4437-8162-49359d477e0d.jpg)
![IMG_5004](https://user-images.githubusercontent.com/112654923/201224751-aa574a74-944e-4243-985b-63ef51a1de07.jpg)

**Comment by ZiggyAtl** [comment]
@jonathanwburr I noticed that the font had been changed on the certificate and its now spaced out much better thanks. In terms of the 'boldness' I'm REALLY sorry to be picky on this one, but with it being the certificate it's important. I just wanted the text making a bit bolder to look like it originally did e.g. the samples above. However it's now much bolder than it originally was, so much so that when I print it out, it's lost the spacing between the letters and they now merge in to each other. Please can you make it more like it originally was (the font in the middle in the picture)
![IMG_5064](https://user-images.githubusercontent.com/112654923/202272668-bf1df13a-301f-4c56-9453-f69d17c1406a.jpg)

**Comment by ZiggyAtl** [comment]
@jonathanwburr sorry but it's still not right. The original font was perfect (the one in the middle in the previous comment I made), but then it changed in to something too light (the one on the top), then something too heavy (the one on the bottom), and now its even lighter than the previous one which was too light. I'm just looking for a font which has the weight of the original certificate we had (the example in the middle in the previous comment).

**Comment by jonathanwburr** [comment]
@ZiggyAtl can you try downloading this one? https://store.comission.art/dab/7273907388595-1147

**Comment by jonathanwburr** [comment]
@ZiggyAtl it should for any new purchases, i don't believe it will apply to orders made previously

**Comment by ZiggyAtl** [comment]
@jonathanwburr ok thanks
