### ISSUE TITLE
The individual artwork page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#17]
https://comission-shopify-hydrogen-ocupop.vercel.app/products/sample-image-1?select%2520a%2520date%2520range=sample%2520art%2520work%25202%253A%252026x26

Should say ‘Membership expires 2024-12-31'

**Comment by tbeck** [comment]
@jonathanwburr - Can you also update the date formatting to match design intentions?

https://xd.adobe.com/view/89d6dd8d-edee-4084-9682-4715dc4ce315-dc85/screen/d5c18f65-8862-47e0-9d17-07233b5070fb

Thanks!

**Comment by ZiggyAtl** [comment]
This issue is fixed when I go in to the actual artwork page, but when I select the artwork on the carousel it has the same problem (doesn't say membership and the date format is incorrect)
![Screen Shot 2022-09-07 at 9 27 06 PM](https://user-images.githubusercontent.com/112654923/189013332-ae3c577e-692c-443a-8f06-61accc332989.png)

**Comment by jonathanwburr** [comment]
@ZiggyAtl I've updated the wording and date formatting for membership expiry in the artwork details when viewing from the mosaic artwork view
