### ISSUE TITLE
Error message unreadable

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#179]
@jonathanwburr  Any chance you could change the font please? For some reason it's not legible in that red background. Maybe needs to be a little bolder? Also it doesn't stay on the screen and disappears after a short while. By the time I looked at it and tried to work out what it was saying (I'm on a relatively small laptop screen) it had gone off the screen. Shouldn't it stay on screen until the user has tried something else?

![Screen Shot 2022-11-16 at 12 51 00 PM](https://user-images.githubusercontent.com/112654923/202257849-6d32a454-d709-46b1-b7ca-3d0c032160a4.png)

**Comment by paulstroot** [comment]
Jon made the text bold in the message. I also added a static error message above the submit button that does not go away.
#183
