### ISSUE TITLE
Hyperlink landing on wrong part of page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#180]
@paulstroot I added a new museum (The Atlanta Museum) and in The Reach I removed it from the previous museum and added it to the Atlanta Museum Collection. Then on the main site I clicked See Artworks, scrolled down to the Reach and clicked See Details. It took me to the bottom of the artwork page, not the top
![Screen Shot 2022-11-16 at 2 52 58 PM](https://user-images.githubusercontent.com/112654923/202280634-459cf45a-a935-450b-a0bc-9d0fa5c8b608.png)

**Comment by paulstroot** [comment]
I haven't been able to recreate this yet but I'm going to look a little deeper this afternoon.

**Comment by paulstroot** [comment]
Hi @ZiggyAtl , if you're able to recreate this, could you let us know if it's all the time, or under certain circumstances? Are you viewing in Safari on Mac?
