### ISSUE TITLE
Update note for each example art

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#19]
Line 16
https://docs.google.com/spreadsheets/d/1tJNNj5aFZVNk7tcfa89u3oHOsrLXZ9yO/edit#gid=474089095 

That Illustrious Feeling
https://comission-shopify-hydrogen.vercel.app/products/that-illustrious-feeling?title=that%2520illustrious%2520feeling%253A%252040x40 

Heels Out
https://comission-shopify-hydrogen.vercel.app/products/heels-out?title=heels%2520out%253A%252040x60

@ZiggyAtl - Can you provide specific content

**Comment by tbeck** [comment]
Thanks!

**Comment by ZiggyAtl** [comment]
The write ups for the artworks and the artists are still mixed up. You need to read the write up (which references the artists) and then match the correct artist with the write up. Also you'll see in Heels Out where there's a [BOX TO INSERT ARTWORK NAME]

**Comment by paulstroot** [comment]
I just fixed this. Just had the artists swapped for the artworks.

**Comment by tbeck** [comment]
Hi @ZiggyAtl - Did you mean to add this comment here? This issue is closed, but maybe we can talk about it during tomorrow's check-in.

Thanks!

> Done. Dropped it in to Github. Btw do I need to respond to an email like this too, or does the fact I added the content in GitHub give you sufficient update? Bill

**Comment by ZiggyAtl** [comment]
Thats weird. I made that comment a long while back, just after I had set up a GitHub account and was learning how it worked.
