### ISSUE TITLE
Loading message when adding to cart needs design

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#27]
When adding a DAB to the cart, there is a momentary "Please wait while we add this DAB to your shopping cart." modal window. This needs some design applied to it. Working on it ~Paul

**Comment by paulstroot** [comment]
@jennyvanderheiden - My thoughts were that instead of throwing up a modal window, I could replace the "select your DAB" button with a spinner, and a small message next to it saying "generating your DAB".

**Comment by jennyvanderheiden** [comment]
I like that idea - I think that works really nice.

**Comment by paulstroot** [comment]
![image](https://user-images.githubusercontent.com/52838369/189453790-9568a3fe-24a8-4224-9fb6-60fabe3e1bd4.png)

This is my current solution. @jennyvanderheiden please feel free to advise design updates.

**Comment by jonathanwburr** [comment]
@paulstroot closing this one for now. We can add more specific issues as they come up
