### ISSUE TITLE
Properly assign the initial unavailable DABs

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#28]
The maximum number of tiles can be set when the artwork product is created. Currently, for development, these tiles are randomly distributed each time the page loads. This random distribution should be consistent each time the DAB selector loads.

For discussion: When will these initially unavailable tiles be released? Should 1 tile be released each time an available DAB is purchased? Or should all of them be released at the a certain percentage of dabs being purchased? Other ideas?

**Comment by jonathanwburr** [comment]
migrated to discussion
