### ISSUE TITLE
Design: Certificate (Desktop)

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#32]

**Comment by tbeck** [comment]
Mobile design: https://xd.adobe.com/view/c43d3fbc-1701-492c-b37e-e66f529f8fa8-916e/screen/c844c853-b751-48bc-b527-d3b38a9b3b4d/

**Comment by tbeck** [comment]
@jennyvanderheiden - flagging this for you that we are shooting to have this implemented prior to next week's demo.

**Comment by jennyvanderheiden** [comment]
Hey all - this is what I was thinking for the [desktop certificate](https://xd.adobe.com/view/c43d3fbc-1701-492c-b37e-e66f529f8fa8-916e/screen/01f4bf86-c38d-4d76-bd84-6e1abcc5c69f/)  

- let me know what you think!

**Comment by tbeck** [comment]
@ZiggyAtl - Just tagging you here for visibility. We will begin implementing this certificate flow like we mentioned in yesterday's call, but feel free to add any feedback based on Jenny's comp:
https://xd.adobe.com/view/c43d3fbc-1701-492c-b37e-e66f529f8fa8-916e/screen/01f4bf86-c38d-4d76-bd84-6e1abcc5c69f/

**Comment by ZiggyAtl** [comment]
Thanks for that. A couple of thoughts on the certificate, although I'm sure you already have these. It needs to be in a format that would print well (in case someone wanted to print it landscape on US letter). It needs the CoM branding / logo on there, and the museum logo. It doesn't need the tax info on there (ie the statement that it is tax deductlble) although the section that says where the money raised is supporting would be good to add.

**Comment by paulstroot** [comment]
The mobile and desktop certificate now shows up for each purchased DAB in the order details page. Once we have implemented the creation of the PDF version of the certificate, it will be formatted to be printed.

To review, you can make a test purchase of some DABs, and then view the "My Account" page.

**Comment by ZiggyAtl** [comment]
I tried to purchase a DAB, and when I got to the checkout screen I clicked on the "Already Have an account, log in" option.

That took me to this screen. 
![Screen Shot 2022-09-12 at 1 54 33 PM](https://user-images.githubusercontent.com/112654923/189724793-a7493d9a-60de-44ea-b161-f7eecba34bc7.png)
My keychain automatically entered the password, but the system then said it was incorrect. I've had this problem before when I was pretty sure the password in my keychain was correct. 

I can't reset it as the password reset is still in development, but you might want to double check that to make sure it's not rejecting valid passwords.

**Comment by paulstroot** [comment]
I will increase the size of the DAB image to meet a minimum size as indicated by the design.

**Comment by paulstroot** [comment]
I have updated the staging site so that clicking on "Print Certificate" should now open up a PDF certificate in a new browser tab for printing. For now, this is only a static PDF, and does not contain the specific information for the purchased DAB. We will update this when we are able to dynamically generate the PDF after an order is completed.

I believe this issue is now ready for review. I'll make sure that generating a PDF with live data is created in a new GitHub Issue

![image](https://user-images.githubusercontent.com/52838369/190212475-2bd86f37-18bc-49e9-95be-6630ff480442.png)
