### ISSUE TITLE
Gifting Feature

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#37]
From Bill:

There was something I forgot to ask on the call. One of the marketing angles we’ll be using is to position a DAB as a unique gift for someone. So what would be our options in that instance if someone bought a DAB for someone else? Can someone buy a DAB and transfer it to someone else’s account, or maybe put it in to an account that the recipient can claim? Pls let me know what you think.

**Comment by jonathanwburr** [comment]
Moved to discussion
