### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#39]
https://comission-shopify-hydrogen-ocupop.vercel.app/account

I was able to set up a new user account, which is great! I do have a couple of questions / things to address

- [x] The design of what I saw when I entered didn't feel very appealing / polished. Is that still a work in progress? 
- [x] It lists an Address book, and I'm not sure what that's in there for?
- [x] When I went to update my phone number I entered just the numbers (no spaces, +1 etc) and got the error message "Enter a valid phone number to use this delivery method'. I also tried it with spaces, +1 etc and it wouldn't accept anything.
- [x] The system didn't require me to validate the email address I put in. Shouldn't I first get an email asking me to validate that email address?
- [x] The reset password system is a bit flaky. When I tried it and clicked on the link which was sent to my email I got this window
![Screen Shot 2022-09-08 at 9 38 41 PM](https://user-images.githubusercontent.com/112654923/189254381-0e01929e-59ff-412b-899e-aeb9ee7a62c9.png)

It looks like there is an error message on there. Also it doesn't look like the rest of the CoMission site (doesn't have logo etc) which might lose us user confidence. It also says password incorrect, which will confuse people. Then when I entered a new password it sent me to this generic Shopify window rather than signing me in
![Screen Shot 2022-09-08 at 9 42 11 PM](https://user-images.githubusercontent.com/112654923/189254599-18e99cbc-3f08-4531-b5ef-5b022fb259d6.png)

I then entered the new password and got the error message 'Password incorrect, please try again'

**Comment by jonathanwburr** [comment]
@ZiggyAtl the reset password flow is in development. Will update you when that's ready.
We will update the login flow and account screen ui.

**Comment by jennyvanderheiden** [comment]
@ZiggyAtl 

In regards to the design comment - curious if you could expand on that. Is it a specific state? For example, before or after logging in?

Happy to discuss if a conversation is needed as well. Thank you!

**Comment by ZiggyAtl** [comment]
Hi Jenny, this was the screen I was referring to. Hope the comments below explain what I was saying;
![Screen Shot 2022-09-12 at 2 36 08 PM](https://user-images.githubusercontent.com/112654923/189730637-aefb7174-cd51-4b3c-8aaf-043d5ec52a4d.png)
 Each of the headings is in a different type (size, bold etc).
It says Account Details at the top, and then again two headings down. 
The logout link looks odd where it is
The edit button beside the second Account Details section is small and looks odd where it is on the far right of the page.
Don't user accounts usually have a menu and then sections? This looks like it's going to be one continuous scroll down the page.

**Comment by jonathanwburr** [comment]
@ZiggyAtl the password reset flow should be working now. You will need to generate a new reset request.

**Comment by ZiggyAtl** [comment]
- [ ] The password reset worked for me. Thanks
- [ ] I don't understand on the reset email though why there is a hyper link to the store, plus another option which says Visit our store. If either of those are clicked it takes the user to this shopify page below, which will be confusing. Shouldn't those 2 options be removed?
![Screen Shot 2022-09-13 at 7 59 09 AM](https://user-images.githubusercontent.com/112654923/189896290-8d5c3bc8-ed1d-4305-8557-7261ca64d176.png)

- [ ] At the bottom of the reset email page it says "If you have any questions, reply to this email or contact us at tom@tastylounge.com"
