### ISSUE TITLE
Order confirmation page

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#40]
After completing an order, the user is taken to the order confirmation page on comission-art-myshopify.com. There are no links on this page to return to the website, I need to hit the back button to return. Do we have the ability to customize this?

**Comment by paulstroot** [comment]
I noticed just now a "return to site" link. Maybe I overlooked this before.

**Comment by jonathanwburr** [comment]
@paulstroot I added that link today, we may need to update the url to our staging instance, but figured out how to add a link
