### ISSUE TITLE
Logo in top left

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#44]
Apple is scanning the text in the logo, and allowing it to be selected. Need to put tag on image saying do not scan this image, its a logo

**Comment by jonathanwburr** [comment]
@ZiggyAtl can you provide a screenshot of the issue?

**Comment by ZiggyAtl** [comment]
Here you go. It's only seeing the image and the first two letters as the logo. The 'Mission' wording is being treated as letters so if anyone clicks on that piece it selects the letters.
![Screen Shot 2022-09-13 at 7 54 16 AM](https://user-images.githubusercontent.com/112654923/189894647-c554735a-5c20-4caf-b138-a486de7d862c.png)

**Comment by jonathanwburr** [comment]
@ZiggyAtl I've updated the logo to not be selectable
