### ISSUE TITLE
Museum partners page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#45]
On this page...  https://comission-shopify-hydrogen-ocupop.vercel.app/pages/museum-partners

Please can you change the call to action button at the end (in the black section) to Learn More and link it to this page
https://comission-shopify-hydrogen-ocupop.vercel.app/pages/for-museums

**Comment by paulstroot** [comment]
Fixed in this update e6a99884f9a39754558c5c964f4eb2e06c56caa7

**Comment by ZiggyAtl** [comment]
Has it been uploaded? When I accessed the page it still looked the same as before
