### ISSUE TITLE
Select your DAB

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#48]
Wherever it appears, the 'Select your DAB' wording/link is obviously a major call to action. Can we therefore highlight it a bit more than it is now? Rather than it just being blue wording, could it be a blue box with white lettering?

**Comment by paulstroot** [comment]
@jennyvanderheiden , can we get some confirmation and/or direction on this so we can get the correct sizing, spacing and padding on the button?

**Comment by jennyvanderheiden** [comment]
Let's do that. Thinking we can utilize the Blue "Select your DAB" button instead of the blue text. See example reference update from mockup[ here](https://gyazo.com/ae05769c1a95ef28b135686b1a43e237)

**Comment by ZiggyAtl** [comment]
Thanks for changing to a button. Could you beef up the white lettering a bit please by making it bold and maybe a point size bigger?

**Comment by paulstroot** [comment]
How does this look @jennyvanderheiden and @ZiggyAtl ?
![image](https://user-images.githubusercontent.com/52838369/189714669-fc23077d-4df4-4003-b205-1f6c30abcd03.png)

**Comment by ZiggyAtl** [comment]
Looks good, thanks. Could you make the Y in your lower case please
