### ISSUE TITLE
FullStory

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#49]
Please can you connect my FullStory account with the website, so I can use it to track users visits around the site.

In case you need to get in to my account to do that, the user name is bill@comission.art and the password is 
mutpEk-9koxty-dagmiw

I was told that there may even be a function in Shopify to just "Implement Full Story' and it automatically does it.

**Comment by paulstroot** [comment]
@jhamlett - Adding you for visibility. Tom will discuss with you.

**Comment by jhamlett** [comment]
@ZiggyAtl FullStory is asking me for a verification code to access the account. Could you pass that along in here or email to j@ocupop.com
