### ISSUE TITLE
DAB selection & cart

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#53]
- [x] On DAB selector screen, the tool tip should appear on highlight, as well as click. Should also appear on unavailable ones, saying that block is unavailable. 
- [x] #93
- [x] Its taking a long time for the DAB to get added to the cart after being selected (10 seconds). Need to reduce this considerably as people will worry there's something wrong with the system, and we could lose them.
- [x] Once the DAB is added to the cart it just brings them back to the artwork screen with no instructions of what to do next. Instead of doing that could we have the page open up to the cart?
- [x] When the user is in dark mode, the things are the wrong color in the cart. It's black text on a black background, and the checkout button is black text (should be white?) on a blue background

**Comment by ZiggyAtl** [comment]
Re #1 Can't we have it appear on hover, and then have it stick once it's clicked (so the user can then scroll down)?

**Comment by paulstroot** [comment]
@tbeck @jonathanwburr , Thoughts on usability on this? Would there need to be some indication that the user needs to click in order to keep the tooltip from going away?

**Comment by paulstroot** [comment]
Re: 

> Once the DAB is added to the cart it just brings them back to the artwork screen with no instructions of what to do next. Instead of doing that could we have the page open up to the cart?

I have updated so that once a DAB is added to the cart, the page automatically navigates to the cart page.

**Comment by paulstroot** [comment]
I'm experimenting with having a minimal tooltip pop up on hover, and a more pronounced tooltip with the purchase button on Click. We are going to review next week and decide what we think about usability.
![image](https://user-images.githubusercontent.com/52838369/190526803-67db2c1b-18f3-4ebb-945b-9d2ef64bd466.png)

**Comment by jonathanwburr** [comment]
@ZiggyAtl Paul added some hover functionality to the dab selector

**Comment by paulstroot** [comment]
I made a new issue #93 out of the second item.

**Comment by ZiggyAtl** [comment]
I tried adding this one to the issues but couldn't. Also this issue may be covered elsewhere, so if it is please ignore this message and close the issue. I selected a DAB while I was not logged in, then selected the checkout option, but it goes to this screen and I thought it should go to a custom CoM log in page?
![Screen Shot 2022-09-20 at 9 20 15 PM](https://user-images.githubusercontent.com/112654923/191393975-67abfcad-9d51-4095-9281-b84f8b0dd832.png)
