### ISSUE TITLE
Navigation bar at top

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#54]
- [x] On mini nav menu at top there are two search options, and we only need one.
- [x] The icons are too small, especially the Cart one. If there's something in there, that is a major call to action and we should be highlighting that, hence wanting it bigger. 
- [x] It also doesn't look right, having a navigation menu above another navigation menu. To address this and the points above, how about we modify it to be something like opensea.io? They have almost the same amount of items at the top, and their layout looks slicker and better laid out than ours. Would welcome your comments on this before making any modifications
- [x] If we did go with the two navigation bars, I think the main CoMission logo needs shifting down. It appears to be centered between the two navigation bars, but it looks like its offset. I think it would need lowering and centering along with the main line of navigation and the blue See Artworks box

**Comment by tbeck** [comment]
@jennyvanderheiden - Let's connect on this and discuss an approach to help resolve some of the issues that @ZiggyAtl is flagging.

There are a few menu states that we need to account for as well. ie... authenticated user, active cart etc.

**Comment by jonathanwburr** [comment]
Ive made most of the style updates, still need to address some different account and cart states
https://gyazo.com/566ab83ce362045d0ef3b056a9d9c69f
logged out / logged in state - are we updating the user icon based on state? Are we replacing the current user icon?
What does cart look like if we have no items in it, is there an icon, or just text?

**Comment by jennyvanderheiden** [comment]
I was thinking we could have two different icons for logged in and logged out - reference: https://gyazo.com/b596a7c90f3a62979d0beba6d58d62fa

Thinking no items in cart is the bag icon - reference:  https://gyazo.com/62f938ff59512857a4b825dd784b9383

**Comment by jonathanwburr** [comment]
@ZiggyAtl we have made some adjustments to the design to address nav
https://gyazo.com/60f8e5abdf4d9742c399f9afa1c0a68d
and is also up on staging
