### ISSUE TITLE
Artwork Images

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#55]
I've had some feedback that the artwork images are unnecessarily big, and take up a lot of space on the page and therefore will require a lot of scrolling when there's multiple ones on a page. The suggestion was to reduce the artwork size and have it more like a card style with the image on top and info below. Like opensea do it.  https://opensea.io/assets?search[query]=bored%20ape

What are your thoughts please?

**Comment by jonathanwburr** [comment]
Reduce column width of image on /products page

**Comment by tbeck** [comment]
Here is a direct link for review: https://comission-shopify-hydrogen-ocupop.vercel.app/products

**Comment by jennyvanderheiden** [comment]
I think this is working well - I'd love to also resize to this on the "Collect" section of the homepage

**Comment by jonathanwburr** [comment]
@ZiggyAtl I added this to the homepage as well https://store.comission.art/

**Comment by ZiggyAtl** [comment]
Thanks Jon. In looking at that I realized the words Available and Collection above it need to be all lower case. Please can you update the A & C (but of course keep the capitals in CoMission)

**Comment by jonathanwburr** [comment]
@ZiggyAtl the copy updates are now up on the homepage
