### ISSUE TITLE
Tax deductible wording

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#57]
Feedback is that the site doesn't highlight well enough that a purchase of a DAB is tax deductible. Therefore we need to add the statement "Your purchase is tax deductible within the guidelines of U.S. law." in a few more places to create more awareness. Please can you add it under the Select Your DAB on the artwork page (where I indicated)
![Screen Shot 2022-09-11 at 5 54 24 PM](https://user-images.githubusercontent.com/112654923/189550521-36172dbf-3827-4f38-96b4-806da1dc48d5.png)

And please can it also be added under the price on the tool tip on the DAB selector tool

**Comment by ZiggyAtl** [comment]
I've just noticed there was a ready for review on this, but the issue doesn't seem to have been addressed at all?

**Comment by tbeck** [comment]
Hi @ZiggyAtl - Taking a look here: https://comission-shopify-hydrogen-ocupop.vercel.app/products/that-illustrious-feeling?membership%2520period=that%2520illustrious%2520feeling%253A%252040x40

The new copy is in place. Can you provide additional details if you are not seeing the same?

Thanks!
<img width="1122" alt="Screen Shot 2022-09-14 at 8 46 12 AM" src="https://user-images.githubusercontent.com/242469/190201988-c663217f-0ea6-4d2c-a8bb-a2aff6cf53c2.png">

**Comment by ZiggyAtl** [comment]
I'm seeing that text, thanks. A few things though. I'd like it to be bigger please, preferably the same size as the Beath Museum or, if that looks too big, the same size as Springfield, OR. 
I'd also like it on the tool tip please, underneath the price.

**Comment by paulstroot** [comment]
We noticed in our meeting that this text does not appear below "Select your DAB" in every occurrence throughout the site. Uploading an update now to fix that.

Pull Request https://github.com/ocupop/comission-shopify-hydrogen/pull/100

**Comment by jonathanwburr** [comment]
@ZiggyAtl we added to the products page grid view and are closing this issue
