### ISSUE TITLE
Customize confirmation email to user.

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#60]
_Originally posted by @paulstroot in https://github.com/ocupop/comission-shopify-hydrogen/issues/29#issuecomment-1244018392_

On order completion, the confirmation email sent to the user should contain some custom information if possible, like the DAB id and certificate link

**Comment by jonathanwburr** [comment]
@ZiggyAtl we will discuss this issue in our Shopify run through

**Comment by ZiggyAtl** [comment]
I've been working on this and trying to combine both the 'next steps' instructions and the 'tax deduction' info in to one email. But it gets a bit long, with too much in it. Is it possible to have two emails that go out after each purchase? If so, I have attached an initial draft for the 'next steps' email. Note I've got a question in there for you, as to what we can add in terms of links / info from Shopify. Happy to jump on a call to explain what I mean.
[Welcome email.docx](https://github.com/ocupop/comission-shopify-hydrogen/files/9711364/Welcome.email.docx)

**Comment by paulstroot** [comment]
If it helps, there the order completion process can be divided into two
steps, which may help with how to think about the emails.

First, there is the "order complete" process, which is typically when the
order has successfully been submitted and payment made. This would be a
good place to talk about tax deductions and benefits of the purchase.

The next step is "fulfillment". This would typically be when a company has
fulfilled the order and shipped it, but for our purposes, it will be when
the Certificate PDF has been generated. An email sent at this time would be
where you would link to the certificate, and mention social sharing and any
other next steps.

Not sure how those two steps fit into the copy that you're working with so
far, but maybe that info will help.

**Comment by paulstroot** [comment]
I was mistaken about my last comment. I just learned that having two emails is actually not a possibility in our situation. The fulfillment email I mentioned is only available to products that are set to be a physical product that gets shipped to the customer, and the email is sent to the fulfillment service. We'll want to gather all of our information to the customer in the one email that gets sent when the order has been completed.

The welcome email you've put together so for @ZiggyAtl is a great start. We can also include in here links to social media, a link to the certificate, images, and more. Also, there are no technical limitations keeping is from selling more than one DAB in an order. We can perhaps discuss how we might section off the welcome email into a few visual groups in this scenario in our next call.

**Comment by paulstroot** [comment]
I played around a bit with your welcome email text, and re-arranged in a way that might work if there was just one DAB, or multiple DABs in an order. This would need some fine-tuning of the copy from @ZiggyAtl and @alex, but it's something to discuss.

https://docs.google.com/document/d/1r9rG6T8Zz7LWT60yR8ucWzEo6T39bpua/edit?usp=sharing&ouid=114955153051386964490&rtpof=true&sd=true

**Comment by paulstroot** [comment]
@ZiggyAtl Attached is what the order confirmation looks like now. Please review. (@alexjlahr , copying you for any copy suggestions)

We will need to work on the second email with the tax exemption information next. (@tom, this is on our list to discuss)

Please review this email and post any update suggestions here. Open a new issue for comments about the second email

![image](https://user-images.githubusercontent.com/52838369/195707553-67460c1a-22d5-40c2-afa2-65ed5e83a67b.png)

**Comment by ZiggyAtl** [comment]
Thanks Paul, it's looking good. A few things, and I think some of the typos are because of incorporating multiple DABs on the order.

1) The second bullet point is meant to include the artist(s) names, i.e. ....by world renowned artist [artist name] in your art collection.
2) The third bullet point says "you have made donationS" even though it lists one museum. It also has the word 'and' before the Museum name. Is this because it anticipated two museum names in the same sentence?
3) Please use the following for the last paragraph;
To quality, all you need to do is click the "View Certificate" button below then share your Digital Art Block(s) on Instagram, Facebook or Twitter, or post a picture of yourself in front of the physical painting you bought a Digital Art Block in. In each instance you also need to tag us @CoMission.Art  Each post gets you an additional entry in the draw.

**Comment by paulstroot** [comment]
Updates made. I forwarded the confirmation email to @ZiggyAtl and @tbeck for review.
