### ISSUE TITLE
CORS issue when adding to Cart

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#69]
@paulstroot I think we're having the same CORS issue when adding dab to cart i'm assuming we need to add https://store.comission.art/ domain 
`Access to fetch at 'https://us-central1-comission-application.cloudfunctions.net/createTempVariant' from origin 'https://store.comission.art' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by paulstroot** [comment]
That's likely it. I'm adding it now. Please test it on your end.
