### ISSUE TITLE
Select DAB doesn't seem to be working

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#70]
I was testing the DAB selection, selected a DAB (I wasn't signed in to my account at this stage, if that info is of use) and then the generating your DAN message came up, but then continued spinning round and never did anything. 

![Screen Shot 2022-09-13 at 8 07 58 AM](https://user-images.githubusercontent.com/112654923/189897669-09090ee2-03af-4962-b578-330db0b9ae42.png)

**Comment by jonathanwburr** [comment]
@ZiggyAtl I think this is probably related to issue #69 https://github.com/ocupop/comission-shopify-hydrogen/issues/69 which Paul pushed a fix and is working for me now. Let me know if that's not the case

**Comment by ZiggyAtl** [comment]
Yes just tested and it's working now. Just another heads up though... when I went to the cart to check out and clicked on the 'Already have an account? log in' option on the checkout page it took me through to this Shopify page. https://comission-art.myshopify.com/password  rather than a CoMission log in page.

Is this being worked on under another issue? If it is already documented elsewhere please feel free to mark this issue closed.

**Comment by jonathanwburr** [comment]
@ZiggyAtl yes aware of the login link from checkout flow. I created new new issue #73 to keep track. Closing this issue
