### ISSUE TITLE
Login link from checkout

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#73]
Yes just tested and it's working now. Just another heads up though... when I went to the cart to check out and clicked on the 'Already have an account? log in' option on the checkout page it took me through to this Shopify page. https://comission-art.myshopify.com/password  rather than a CoMission log in page.

Is this being worked on under another issue? If it is already documented elsewhere please feel free to mark this issue closed.

_Originally posted by @ZiggyAtl in https://github.com/ocupop/comission-shopify-hydrogen/issues/70#issuecomment-1245654414_

**Comment by tbeck** [comment]
Duplicate: #96
