### ISSUE TITLE
Repeated info on artwork page

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#77]
I've just realized the artwork info is repeated on the Artwork page
https://comission-shopify-hydrogen-ocupop.vercel.app/products/that-illustrious-feeling?membership%2520period=that%2520illustrious%2520feeling%253A%252040x40

I hadn't been scrolling down, but saw it when I checked on mobile. Everything is repeated further down the page. It also says 100% tax deductible which shouldn't be said anywhere on the site.

**Comment by jonathanwburr** [comment]
@ZiggyAtl I've removed this section.
