### ISSUE TITLE
DAB Selector

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#8]
Interactivity is not fully functional yet. It’s partially working to get an idea of where we’re heading.

**Comment by tbeck** [comment]
Currently working on this in the Museum Application as well.
https://github.com/ocupop/comission-application

**Comment by jonathanwburr** [comment]
@tbeck @paulstroot closing this issue. We can add more specific tasks related to the dab selector as they come up
