### ISSUE TITLE
Custom spinner or progress bar used in DAB creation

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#87]

**Comment by jennyvanderheiden** [comment]
Was thinking we could "spin" this spinner - it is the interior shapes of the logo. I exported as PNG and SVG - let me know what works or if you need another format. Found [here](https://www.dropbox.com/sh/uxr2lwegsu8ujv8/AAAHdKY7nGyvUvZJHJedQZCva?dl=0)
