### ISSUE TITLE
Add to cart

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#9]
Still in production

- [x] Loading message when adding to the cart: When adding a DAB to the cart, there is a momentary "Please wait while we add this DAB to your shopping cart." modal window. This needs some design applied to it. 

- [x] Properly pass all data for the tile to be displayed in the cart and checkout

- [x] Generate the tile image when the DAB is added to the cart

- [ ] Jenny creating custom spinner

- [x] I saw there was a DAB in my cart so I went in and deleted it. I then went through the process of selecting a new DAB and adding to the cart, but when the cart opened there were two DABS in there. I then deleted both DABS and the next screen which came up said something about me having no art and helping me to select a piece. It had thumbnails of the two paintings so I selected Illustrious Feeling and got an error page (below) at this address  https://comission-shopify-hydrogen-ocupop.vercel.app/products/that-illustrious-feeling?membership%2520period=that%2520illustrious%2520feeling%253A%252040x40
![Screen Shot 2022-09-14 at 5 16 27 PM](https://user-images.githubusercontent.com/112654923/190264185-607d6e9f-8220-46f3-9f20-0dda7ac21399.png)

From that screen I couldn't click on the back button so I clicked on the home option and got this screen

![Screen Shot 2022-09-14 at 5 18 19 PM](https://user-images.githubusercontent.com/112654923/190264562-9be1ac04-38eb-4ac3-b091-a81c7232143f.png)

**Comment by paulstroot** [comment]
I've added a spinner to replace the "Select your DAB" button while the site is working. Jenny said that she would work on creating a custom spinner graphic for comission.

I have staged these updates on development and just need to test properly before pushing to the staging site. Jon and Tom, please let me know if you encounter any issues with adding to the cart.
