### ISSUE TITLE
Can we also include in the tip a list of the benefits that come with each DAB? The more places we can have that the better.

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#93]

**Comment by paulstroot** [comment]
Let's discuss this a bit first to decide what this list of benefits would look like, how long the text would be, etc., to figure out if the tooltip is the best place for this.

**Comment by tbeck** [comment]
@ZiggyAtl - Marking this as ready for review so that we can discuss in our weekly meeting. It is our suggestion that we do not include benefit content in the tooltip because it creates a bad user experience.
