### ISSUE TITLE
Notifications: update border radius and replace shop url

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#99]
This assignment should be on the top of all system notifications:
`{% assign custom_store_url = 'https://store.comission.art' %}`

replace all instances of `{{shop.url}}` with `{{ custom_store_url }}`

Style settings for buttons to remove border radius:
`.button__cell { background: {{ shop.email_accent_color }}; border-radius: 0; }`

**Comment by jonathanwburr** [comment]
@tbeck I've gone through and updated all the notifications in shopify, we can either send test notifications or mark this as complete

**Comment by tbeck** [comment]
Thanks @jonathanwburr
